server:
  port: 8084

spring:
  datasource:
    username: root
    password: wjz1108
    url: jdbc:mysql://localhost:3306/2018011322?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
